version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - mynetwork
    env_file:
      - ../.env
    restart: always

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - mynetwork
    env_file:
      - ../.env
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - mynetwork
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - ../.env
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/edrouot/data/wordpress
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/edrouot/data/mariadb

networks:
  mynetwork:
    name: mynetwork
    driver: bridge
